### ISSUE TITLE
师傅您好，出现以下报错

### ISSUE THREAD

**Issue by 98Kstar** [0cat-r/jslink_XRAY#1]
师傅您好在扫描某些站点的时候 会出现以下报错
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 8718: invalid start byte

**Comment by 0cat-r** [comment]
师傅好 加我微信 我看看哈
微信号:r-0cat




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0cat-r/jslink_XRAY"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 中午11:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[0cat-r/jslink_XRAY] 师傅您好，出现以下报错 (#1)





 
师傅您好在扫描某些站点的时候 会出现以下报错
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 8718: invalid start byte
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 0cat-r** [comment]
师傅好，可以截取一个完整的报错信息吗

**Comment by 98Kstar** [comment]
![image](https://user-images.githubusercontent.com/41816999/131946473-d103e7ec-75dc-44ba-9d76-501a896cfe4c.png)
是这样的

**Comment by 0cat-r** [comment]
师傅可以加您一个联系方式吗

**Comment by 0cat-r** [comment]
问题刚刚已经被修复，忽略了不能被 utf-8 编码的字节，即：
print(cmd_out.decode(errors='ignore'))
时间过去很久了，我也才想起来。这个脚本是之前长亭rad还没发布的时候写的。现在师傅可以去看看更好的策略和方法，感谢师傅使用。
